export const FETCHED_QUESTIONS_FROM_DATABASE = 'FETCHED_QUESTIONS_FROM_DATABASE';
export const SET_QUIZ_QUESTIONS = 'SET_QUIZ_QUESTIONS';
export const START_QUIZ = 'START_QUIZ';
export const QUIZ_COMPLETE = 'QUIZ_COMPLETE';
export const INCREMENT_SCORE = 'INCREMENT_SCORE';
export const RESTART_QUIZ = 'RESTART_QUIZ';
